[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["Felix Gruber <felgru@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18.0"
image = "0.23.4"
approx = "0.3.2"
yaml-rust = "0.4.3"
